include("test_LBFGS.jl")
include("test_lasso.jl")
include("test_warm_srt.jl")
include("test_lasso_random.jl")
include("test_lasso_complex.jl")
include("test_lasso_multidim.jl")
include("test_matcomp.jl")
