
include("composite/compositeFunction.jl")
include("composite/leastSquares.jl")
include("composite/smooth.jl")
include("composite/split.jl")
include("composite/absorb_merge.jl")
include("composite/norm.jl")
include("composite/box.jl")
include("composite/hingeLoss.jl")
include("composite/indBallRank.jl")
